### ISSUE TITLE
NPX support

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/create-block#14]
Rather than ask people to copy/paste folders from the `/create-block` directory to `/wp-content/plugins`, let's add support for NPX.

Ideally, you'd run `npx @webdevstudios/create-block NameSpace/BlockName` from inside `/wp-content/plugins`.

**My initial testing shows this already works, but I'd like others to verify.** 

- [ ] Verify the `npx @webdevstudios/create-block NameSpace/BlockName` command works across operating systems
- [ ] Update the README.md to feature this command as the defacto way to use `create-block`

**Comment by donmhico** [comment]
+1 I can also confirm that it works for me. I'm in a MacOS.
