### ISSUE TITLE
Replace wdsbs with {{ textdomain }}

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/create-block#9]
This is great stuff. Thanks for all the hard work you've put into this. 👍 

One note on the current placeholders in the templates.

In [lib/templates/wds/src/block/rich-text/index.js.mustache](https://github.com/WebDevStudios/create-block/blob/6b68afdf81ca1bd5743fecf565455102f79494c3/lib/templates/wds/src/block/rich-text/index.js.mustache#L22) I think the text domain `wdsbs` should be replaced with `{{ textdomain }}` (the same value we use for the text domain in [lib/templates/wds/%24slug.php.mustache](https://github.com/WebDevStudios/create-block/blob/master/lib/templates/wds/%24slug.php.mustache#L17))

I think this same replacement also comes up in other templates.

**Comment by donmhico** [comment]
Hey @salcode! Thanks for pointing this out. I've addressed this issue in this PR https://github.com/WebDevStudios/create-block/pull/11
